### ISSUE TITLE
Contract API overhaul - Typechain Fork

### ISSUE THREAD

**Issue by HughParry** [prosopo/captcha#685]
### Topic which brought this up:

> Typechain generates a contract class with requires a signature for definitely the write operations, but also possibly the read operations.
> 
> We require a client being able to make read calls without explicitly using an account.

### Discussion points:

1. How can we seperate concerns of the use cases for the Contact API (e.g. read/write/sign/something else)
2. When and how do we overhaul
3. How do we maintain current methods for clients
4. Is it ok to use a public and shared account to make public calls?

**Comment by forgetso** [comment]
Typechain fork is underway.

**Comment by goastler** [comment]
1. I don't think we need to separate the concerns as that's what typechain has at the moment, and it's not great. E.g. queries and tx are separated out but are really duplicates. I think we just focus on building a system which translates the metadata for a contract into a bunch of methods. Then you specify your contract address and voila, smart contract calls
2. we don't need to, this is our typechain now and because it's so poorly strucutred I'm not concerned about backwards compat
3. see 2.
4. yes, why would it not be?

@HughParry what are your thoguths on the above? specifically no. 1

**Comment by HughParry** [comment]
I think separation of concerns for read/write/whatever was mostly a question from the viewpoint of non web3 users querying the contract with only read operations (though this isn't actually possible anyway). We now use default accounts to sort this.

Agree with your points 👍

**Comment by goastler** [comment]
I've migrated this ticket to specific issues, closing.
